### ISSUE TITLE
incorrect flow of forms after being accepted/ rejected at doctor or accounts end 

### ISSUE THREAD

**Issue by sanchit-sinha** [shoryak/hc_reimbursement#30]
@phoenix-23 Kindly, check this the flow of form. 
For eg: The form being rejected by ``accounts`` is shown as accepted in ``hcadmin page``. 
I feel the major issue is in the respective ``.html files`` and not in the ``views.py file``.

**Comment by phoenix-23** [comment]
This was done intentionally. The forms accepted by a certain party will remain accepted by them. It will only be shown rejected to patient if anyone of them rejects

**Comment by Gaukm01** [comment]
The Accepted/Rejected in one Admin user dashboard contains the forms Accepted/Rejected by that specific user, Status of Transaction is for information related to what happened in later stages.

**Comment by phoenix-23** [comment]
Please let the person who raised the issue, decide if this issue is resolved

**Comment by sanchit-sinha** [comment]
> Please let the person who raised the issue, decide if this issue is resolved @sanchit-sinha

I'll check the logic once again and let you know ! 🤔

**Comment by sanchit-sinha** [comment]
Kindly explain this one 
https://github.com/shoryak/hc_reimbursement/blob/296ceefb620e8c9c1338a97873c32c15f7c78589/src/user/templates/doctor_dashboard.html#L353

The form that is rejected by hc admin is showed as accepted in doctors dashboard, even if the doctor has not accepted/rejected it

**Comment by Gaukm01** [comment]
The allowed status (only status can be either of allowed status) shows these transactions are those which were already accepted by the Doctor (After receiving the request from HC Admin first time). According to our workflow for reaching these statuses: the form has to pass via 'Form submitted, Waiting Doctor approval' statuses. So, For these transactions doctor has accepted the forms. Now afterwards these can be Approved/Rejected by HC Admin or Accounts, but since these were already accepted by the Doctor, so the form is shown here in the Accepted Forms.
@phoenix-23 please add if I missed something.

**Comment by phoenix-23** [comment]
@sanchit-sinha yes you're right. There is a flaw in this as you have rightly pointed out. As discussed earlier, the main logic sequence for form transaction path was _patient_ \rightarrow _HC Admin_ (can only forward to doctor) \rightarrow _Doctor_ (accept/reject the form) \rightarrow _HC Admin_ (accept/reject the form) \rightarrow _Accounts Office_ (accept/reject the form). There this logic would stand as any status after 'Waiting Doctor Approval" and not "Rejected by Doctor" would be assumed to be passed by the doctor. 

Bugt presently, there is still a 'Reject' button/option present for the HC Admin when the form comes to it the first time (when it can ONLY forward it to the doctor). Due to that this problem is arising. Thanks for bringing this issue to light. The solutions are-
- to make changes in the transaction path
- just remove the 'Reject' button from HC Admin page for forms that has come for the first time to their dashboard.

**Comment by Gaukm01** [comment]
@phoenix-23 I didn't understand the problem completely but is it that accepted forms here for a given doctor is showing forms that are not even directed to them because of what status we are checking is not doing any checking for who is the doctor.  
Afaik when HC Admin receives a form for first-time, it can either reject or Pass to Doctor Confirmation. So maybe we should not remove the 'Reject' button from HC Admin.
Can we just add an extra check that the 'Medical Advisor' mentioned in the form is the same as this doctor, I think this will resolve the issue. @sanchit-sinha?

**Comment by phoenix-23** [comment]
No @Gaukm01, the problem here is that since we have provided the 'Reject' option for first time forms at HC Admin side, these forms can be rejected by HC Admin and at the backend they will have the status 'Rejected by HCAdmin". And following the logic in the line of code in question, this will be interpreted as a form accepted by doctor, which is not true as the form never reached the doctor's dahsboard

**Comment by sanchit-sinha** [comment]
> @sanchit-sinha yes you're right. There is a flaw in this as you have rightly pointed out. As discussed earlier, the main logic sequence for form transaction path was _patient_ -> _HC Admin_ (can only forward to doctor) -> _Doctor_ (accept/reject the form) -> _HC Admin_ (accept/reject the form) -> _Accounts Office_ (accept/reject the form). There this logic would stand as any status after 'Waiting Doctor Approval" and not "Rejected by Doctor" would be assumed to be passed by the doctor.
> 
> But presently, there is still a 'Reject' button/option present for the HC Admin when the form comes to it the first time (when it can ONLY forward it to the doctor). Due to that this problem is arising. Thanks for bringing this issue to light. The solutions are-
> 
>     * to make changes in the transaction path
> 
>     * just remove the 'Reject' button from HC Admin page for forms that has come for the first time to their dashboard.
> 
> 
> I suggest we go with second option. Please suggest @sanchit-sinha @Gaukm01 @shoryak

I think there should be a reject button right else, hc-admin will have only one option that is to pass the form to the doctor right??

**Comment by phoenix-23** [comment]
yes @sanchit-sinha 
basically the form is passing through the HC Admin twice. Giving an accept/reject option in both the times seems redundant hence the form-flow was decided. So, when the first time forms arrive at the HC Admin dashboard, they should be only forwardable to the doctor (though this seems redundant too but this helps the HC Admin to add any feedback before forwarding the request to the doctor)

**Comment by sanchit-sinha** [comment]
Cool, I think we can do that for the time being .. @phoenix-23 Kindly look into it.. 

I will suggest go through all the logic once again.. The reject button in Accounts section also seem to be redundant.

**Comment by sanchit-sinha** [comment]
Or can we do this 
If the form is rejected by HCadmin or Accounts mark it just as ``rejected``

**Comment by phoenix-23** [comment]
@sanchit-sinha I guess following the logic that the HC side verification involves only verifying if the claim is true and the accounts side verification involves if the reimbursement for that specific cause is allowed. If this logic is correct then the reject button would be required for accounts office. Else, if it seems fit to everyone, we can remove the reject button from accounts too

**Comment by phoenix-23** [comment]
@sanchit-sinha so what you're suggesting is we can replace the statuses "Rejected by HCAdmin" and "Rejected by Accounts" with "Rejected" (keeping the reject button in accounts dashboard intact) ?

**Comment by sanchit-sinha** [comment]
> @sanchit-sinha so what you're suggesting is we can replace the statuses "Rejected by HCAdmin" and "Rejected by Accounts" with "Rejected" (keeping the reject button in accounts dashboard intact) ?

Yes. 
Will it cause any issues ?

**Comment by phoenix-23** [comment]
Yes, I think you're right. These two statuses can be merged into one

**Comment by Gaukm01** [comment]
> No @Gaukm01, the problem here is that since we have provided the 'Reject' option for first time forms at HC Admin side, these forms can be rejected by HC Admin and at the backend they will have the status 'Rejected by HCAdmin". And following the logic in the line of code in question, this will be interpreted as a form accepted by doctor, which is not true as the form never reached the doctor's dahsboard

If this is the issue,can we just create a different status for when form is rejected by HC office without sending the form to the doctor.

I think replacing the "rejected by ...." by just "rejected" will remove the info for patient that in which stage the form actually got rejected.  Because of this we had introduced multiple reject options for each role.
Also the form being confirmed twice by HC Admin, is the part of intended workflow, so we should not see it as redundant, as it's what is required.
We don't know the cause for which any admin user will reject the form, so we should not go with restricted reasons for rejection.

For accepted part we have created two types of status for HC Admin actions, but forgot to add so for rejected part logic. So adding another status for first time rejection by HC admin should resolve the issue.

**Comment by sanchit-sinha** [comment]
> I think replacing the "rejected by ...." by just "rejected" will remove the info for patient that in which stage the form actually got rejected. Because of this we had introduced multiple reject options for each role. @sanchit-sinha

Btw, Why is it important for patient to know at which stage it got rejected? It will not help him/her in any way . If the form is being rejected he has to anyway apply again. It would have been helpful in a system in which patient can interact directly with those who rejected its form.
But yeah that will be the issue if we merge the statuses

**Comment by phoenix-23** [comment]
Presently, the purpose of having different statuses was purely to implement the kind of logic where different verification points can have different statuses. Like if a doctor accepts the form but the HC Admin rejects it, then the form should be under the "Accepted form" category for the doctor, while it should be under the "Rejected form" category for the HC Admin. This can be done only via different statuses for different levels pf verification.
The purpose was never to show the patient where the form got rejected, but keeping the multiple the status gives us the flexibility to show them that.

I am in favour of the merging of the statuses. Please react if you agree

**Comment by phoenix-23** [comment]
Present Statuses - _Form Submitted_, _Waiting Doctor approval_, _Waiting HC Admin approval_, _Sent to Accounts_,  _Approved by Accounts_, _Rejected by Doctor_, _Rejected by HC Admin_, _Rejected by Accounts_

New Statuses - _Form Submitted_, _**Form Rejected**_, _Waiting Doctor approval_, _Waiting HC Admin approval_, _Sent to Accounts_,  _**Approved** ~~by Accounts~~_, _Rejected by Doctor_, _~~Rejected by HC Admin~~_, _~~Rejected by Accounts~~_, _**Rejected**_

If agreed, please react

**Comment by Gaukm01** [comment]
> Btw, Why is it important for patient to know at which stage it got rejected? It will not help him/her in any way . If the form is being rejected he has to anyway apply again. It would have been helpful in a system in which patient can interact directly with those who rejected its form. But yeah that will be the issue if we merge the statuses

Yeah, it doesn't seem much helpful from the patient side. But I forgot to mention, this will be also available to admin sides where the form finally got rejected, so in case of any discrepancies (like the correct form being rejected again and again without any comment), the patient/other admin can directly contact the person/role responsible for this. 
I think we should not remove some info that we are providing right now, for fixing an issue, and should think of another way to fix it if possible.

**Comment by Gaukm01** [comment]
> Present Statuses - _Form Submitted_, _Waiting Doctor approval_, _Waiting HC Admin approval_, _Sent to Accounts_, _Approved by Accounts_, _Rejected by Doctor_, _Rejected by HC Admin_, _Rejected by Accounts_
> 
> New Statuses - _Form Submitted_, _**Form Rejected**_, _Waiting Doctor approval_, _Waiting HC Admin approval_, _Sent to Accounts_, _**Approved** ~by Accounts~_, _Rejected by Doctor_, _~Rejected by HC Admin~_, _~Rejected by Accounts~_, _**Rejected**_
> 
> If agreed, please react @sanchit-sinha @Gaukm01

If we are adding a new status, then we don't need to merge both the rejected by Accounts/HC Admin. Our issue will be removed because of newly added status? @sanchit-sinha 

Also, we will have two types of forms Rejected by HC Admin. We can show both of them under the same Rejected Forms section of HC Admin Dashboard, by changing the status here
https://github.com/shoryak/hc_reimbursement/blob/296ceefb620e8c9c1338a97873c32c15f7c78589/src/user/templates/hcadmin_dashboard.html#L973
and adding "Form Rejected" too in here.

**Comment by sanchit-sinha** [comment]
> > Present Statuses - _Form Submitted_, _Waiting Doctor approval_, _Waiting HC Admin approval_, _Sent to Accounts_, _Approved by Accounts_, _Rejected by Doctor_, _Rejected by HC Admin_, _Rejected by Accounts_
> > New Statuses - _Form Submitted_, _**Form Rejected**_, _Waiting Doctor approval_, _Waiting HC Admin approval_, _Sent to Accounts_, _**Approved** ~by Accounts~_, _Rejected by Doctor_, _~Rejected by HC Admin~_, _~Rejected by Accounts~_, _**Rejected**_
> > If agreed, please react @sanchit-sinha @Gaukm01
> 
> If we are adding a new status, then we don't need to merge both the rejected by Accounts/HC Admin. Our issue will be removed because of newly added status? @sanchit-sinha
> 
> Also, we will have two types of forms Rejected by HC Admin. We can show both of them under the same Rejected Forms section of HC Admin Dashboard, by changing the status here
> 
> https://github.com/shoryak/hc_reimbursement/blob/296ceefb620e8c9c1338a97873c32c15f7c78589/src/user/templates/hcadmin_dashboard.html#L973
> 
> and adding "Form Rejected" too in here.

So if you want to keep the statuses as it is. I think we can do so without adding any new status.
We will just have to update the logic for displaying different forms in the different tables .
@phoenix-23 will we have to make any other changes as well in that case?

**Comment by phoenix-23** [comment]
We can keep the statuses as it is, but we will have to add at least one new status ('Form Rejected') to prevent first time forms rejected by hcadmin to show up under rejected forms of doctors

**Comment by sanchit-sinha** [comment]
> We can keep the statuses as it is, but we will have to add at least one new status ('Form Rejected') to prevent first time forms rejected by hcadmin to show up under rejected forms of doctors

Make it ``Form rejected before doctor approval`` or something like that so that it does not create any issue in future

**Comment by Gaukm01** [comment]
*Rejected by HC admin* rkh dete isko, and next wale ko *Rejected by HD Admin (after doctor verification)* krskte.

**Comment by phoenix-23** [comment]
Ok, making the said changes.

**Comment by sanchit-sinha** [comment]
resolved in #35 !
